### ISSUE TITLE
更新闪退

### ISSUE THREAD

**Issue by wcwq98** [gohj99/Telewatch#9]
在oppowatch2 上点检测更新时会闪退。大佬有兴趣修改wxwear(微信儿童版的修改版)吗，有兴趣的话，我去尝试问原作者要逆向出来的源代码

**Comment by wcwq98** [comment]
还有希望能内置socks代理 ，手表挂梯子发热不小

**Comment by gohj99** [comment]
我会在将来修复更新页面闪退的问题，代理后续应该会做

wcwq98 ***@***.***> 于 2024年10月13日周日 下午5:57写道：

**Comment by gohj99** [comment]
如果没有其他问题，请关闭issues

**Comment by wcwq98** [comment]
好吧

**Comment by wcwq98** [comment]
好
